### ISSUE TITLE
The text of the notifications is cut in Vertical mode.

### ISSUE THREAD

**Issue by xBreaKOuTz** [Baw-Appie/Axon#1]
![IMG_1295](https://user-images.githubusercontent.com/34798425/68597322-0f392000-049d-11ea-9ea6-3be7ae37cb54.PNG)

If i disable axon in icleaner or disable the vertical mode the problem seems to be solved but i want to use axon :)
If i disable all other tweaks, the notification is less affected.

![IMG_1297](https://user-images.githubusercontent.com/34798425/68597289-01839a80-049d-11ea-80a4-6338270edfd5.PNG)

Can you fix it please ?

Edit: I'm on iPhone XS 12.1

**Comment by Baw-Appie** [comment]
It's not perfect but it has been fixed. In iOS 13 it works perfectly.

**Comment by xBreaKOuTz** [comment]
The text is still cut for me..
iPhone XS iOS 12.1 Axon 0.2.3

**Comment by Baw-Appie** [comment]
This fix will be included in 0.2.4. The update will be displayed on
December 1st.


2019년 11월 27일 (수) 오후 7:11, xBreaKOuTz <notifications@github.com>님이 작성:

**Comment by xBreaKOuTz** [comment]
Ok ok thanks

**Comment by xBreaKOuTz** [comment]
The bug is still present in 0.2.4
https://imgur.com/gallery/wLVALG0

**Comment by xBreaKOuTz** [comment]
I specify that I am on chimera

**Comment by xBreaKOuTz** [comment]
The bug is still present 14.3 
![C644C4E6-0ED9-4BBC-BE16-7474AC75D60E](https://user-images.githubusercontent.com/34798425/113608575-0ffec300-964b-11eb-9049-aee923c8dbe3.png)
